services:
  traefik:
    image: traefik:v3.6

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"
      - "8081:8080"

  postgres_osm:
    image: postgis/postgis:15-3.4
    restart: unless-stopped

    command: -c config_file=/etc/postgresql.conf

    volumes:
      - postgres_osm_data:/var/lib/postgresql/data
      - ./postgres_osm/postgres.conf:/etc/postgresql.conf
      - ./postgres_osm/init:/docker-entrypoint-initdb.d/

    environment:
      POSTGRES_USER: ${POSTGRES_OSM_USER}
      POSTGRES_PASSWORD: ${POSTGRES_OSM_PASSWORD}
      POSTGRES_DB: ${POSTGRES_OSM_DB}

    ports:
      - "5433:5432"

  omt_tileserver_gl:
    image: "maptiler/tileserver-gl:latest"
    command:
      - --port
      - "${TPORT:-8080}"
      - --config
      - "/style/config.json"
    ports:
      - "${TPORT:-8080}:${TPORT:-8080}"
    volumes:
      - ${OPENMAPTILES_DIR}/data:/data
      - ${OPENMAPTILES_DIR}/style:/style
      - ${OPENMAPTILES_DIR}/build:/build

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omt_tileserver_gl.rule=Host(`omt_tileserver_gl.localhost`)"
      - "traefik.http.routers.omt_tileserver_gl.entrypoints=web"
      - "traefik.http.services.omt_tileserver_gl.loadbalancer.server.port=8080"

  core_service:
    build:
      context: ../../
      dockerfile: infra/geo/core_service/Dockerfile
    restart: unless-stopped

    environment:
      RUST_LOG: info
      HOST: 0.0.0.0
      PORT: 8080
      POSTGRES_OSM_URL: postgres://${POSTGRES_OSM_USER}:${POSTGRES_OSM_PASSWORD}@postgres_osm:5432/${POSTGRES_OSM_DB}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.jlh_maps.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

volumes:
  postgres_osm_data: