//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "unitable")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub osm_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub osm_key: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attrs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "custom(\"geometry\")", nullable)]
    pub geom: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
