import type { BaseRoutingRequest, LatLon, Trip, ValhallaWarning } from './common.js'

/** Centroid request. Valhalla currently mentions this service in the API overview but has sparse public docs.
 *
 * @see https://valhalla.github.io/valhalla/api/
 */
export type CentroidRequest = BaseRoutingRequest

/** Centroid response. */
export interface CentroidResponse {
  /** Correlation id echoed from the request. */
  id?: string
  /** Returned centroid coordinate when provided by the service. */
  centroid?: LatLon
  /** Route-like trip when provided by the service. */
  trip?: Trip
  /** Non-fatal warnings generated by Valhalla. */
  warnings?: ValhallaWarning[]
  /** Additional response values returned by Valhalla. */
  [key: string]: unknown
}
