import type { FeatureCollection, GeoJsonProperties, Geometry } from 'geojson'
import type {
  CostingModel,
  CostingOptionsByModel,
  ValhallaLocation,
  ValhallaWarning,
} from './common.js'

/** Expansion request for exploring the routing graph around an origin.
 *
 * @see https://valhalla.github.io/valhalla/api/expansion/api-reference/
 */
export interface ExpansionRequest {
  /** Origin locations for graph expansion. */
  locations: ValhallaLocation[]
  /** Costing model used during expansion. */
  costing: CostingModel
  /** Options keyed by costing model name. */
  costing_options?: CostingOptionsByModel
  /** Edge properties to include in GeoJSON feature properties. */
  expansion_properties?: string[]
  /** Skip opposite-direction edges when true. */
  skip_opposites?: boolean
  /** Correlation id echoed by Valhalla. */
  id?: string
  /** Valhalla accepts endpoint-specific extension fields. */
  [key: string]: unknown
}

/** GeoJSON expansion response. */
export interface ExpansionResponse extends FeatureCollection<Geometry, GeoJsonProperties> {
  /** Correlation id echoed from the request. */
  id?: string
  /** Non-fatal warnings generated by Valhalla. */
  warnings?: ValhallaWarning[]
}
