import type { Feature, FeatureCollection, GeoJsonProperties, Geometry } from 'geojson'
import type {
  CostingModel,
  CostingOptionsByModel,
  Units,
  ValhallaLocation,
  ValhallaWarning,
} from './common.js'

/** One time or distance contour in an isochrone request. */
export interface Contour {
  /** Contour travel time in minutes. */
  time?: number
  /** Contour travel distance in requested units. */
  distance?: number
  /** Optional hex color used by Valhalla in GeoJSON properties. */
  color?: string
}

/** Isochrone request.
 *
 * @see https://valhalla.github.io/valhalla/api/isochrone/api-reference/
 */
export interface IsochroneRequest {
  /** One or more center locations. */
  locations: ValhallaLocation[]
  /** Costing model used for reachability. */
  costing: CostingModel
  /** Time or distance contours to generate. */
  contours: Contour[]
  /** Options keyed by costing model name. */
  costing_options?: CostingOptionsByModel
  /** Return polygons when true; linestring contours when false. */
  polygons?: boolean
  /** Remove smaller contours; 1 keeps only the largest contour per value. */
  denoise?: number
  /** Generalization tolerance in meters. */
  generalize?: number
  /** Include input and snapped locations in the GeoJSON response. */
  show_locations?: boolean
  /** Distance units used for distance contours. */
  units?: Units
  /** Correlation id echoed by Valhalla. */
  id?: string
  /** Valhalla accepts endpoint-specific extension fields. */
  [key: string]: unknown
}

/** One GeoJSON feature in an isochrone response. */
export type IsochroneFeature = Feature<Geometry, GeoJsonProperties>

/** GeoJSON isochrone response. */
export interface IsochroneResponse extends FeatureCollection<Geometry, GeoJsonProperties> {
  /** Correlation id echoed from the request. */
  id?: string
  /** Non-fatal warnings generated by Valhalla. */
  warnings?: ValhallaWarning[]
}
