import type {
  CostingModel,
  CostingOptionsByModel,
  ValhallaLocation,
  ValhallaWarning,
} from './common.js'

/** Locate request for inspecting graph correlation near one or more points.
 *
 * @see https://valhalla.github.io/valhalla/api/locate/api-reference/
 */
export interface LocateRequest {
  /** Input locations to correlate against the routing graph. */
  locations: ValhallaLocation[]
  /** Optional costing model used to filter candidate edges. */
  costing?: CostingModel
  /** Options keyed by costing model name. */
  costing_options?: CostingOptionsByModel
  /** Include additional edge/node attribution when true. */
  verbose?: boolean
  /** Correlation id echoed by Valhalla. */
  id?: string
  /** Valhalla accepts endpoint-specific extension fields. */
  [key: string]: unknown
}

/** Edge candidate returned by /locate. */
export interface LocateEdge {
  /** Latitude of the correlated point on the edge. */
  correlated_lat?: number
  /** Longitude of the correlated point on the edge. */
  correlated_lon?: number
  /** Position along the edge from 0 to 1. */
  percent_along?: number
  /** Distance in meters from input point to candidate. */
  distance?: number
  /** OpenStreetMap way id when available. */
  way_id?: number
  /** Valhalla graph edge id when available. */
  id?: string
  /** Edge names. */
  names?: string[]
  /** Additional edge attributes returned by Valhalla. */
  [key: string]: unknown
}

/** Locate result for one input location. */
export interface LocateResponse {
  /** Original input latitude. */
  input_lat?: number
  /** Original input longitude. */
  input_lon?: number
  /** Candidate graph nodes when returned. */
  nodes?: Record<string, unknown>[]
  /** Candidate graph edges. */
  edges?: LocateEdge[]
  /** Non-fatal warnings generated by Valhalla. */
  warnings?: ValhallaWarning[]
  /** Correlation id echoed from the request. */
  id?: string
  /** Additional response values returned by Valhalla. */
  [key: string]: unknown
}
